// Array of cex categories that maps to the local category id
export const CEX_CATEGORY_MAPPER_ARRAY = [
    {id: 1, name: 'Atari Jaguar Consoles', localCategoryId: 1},
    {id: 2, name: 'Atari Jaguar Software', localCategoryId: 2},
    {id: 3, name: 'Atari Lynx Consoles', localCategoryId: 3},
    {id: 4, name: 'Atari Lynx Software', localCategoryId: 4},
    {id: 5, name: '3DS Consoles', localCategoryId: 5},
    {id: 6, name: '3DS Games', localCategoryId: 6},
    {id: 7, name: 'Nintendo DS Consoles', localCategoryId: 7},
    {id: 8, name: 'Nintendo DS Games', localCategoryId: 8},
    {id: 9, name: 'Nintendo 64 Consoles', localCategoryId: 9},
    {id: 10, name: 'Nintendo 64 Software', localCategoryId: 10},
    {id: 11, name: 'NES Consoles', localCategoryId: 11},
    {id: 12, name: 'NES Software', localCategoryId: 12},
    {id: 13, name: 'Game Boy Consoles', localCategoryId: 13},
    {id: 14, name: 'Game Boy Software', localCategoryId: 14},
    {id: 15, name: 'GameCube Consoles', localCategoryId: 15},
    {id: 16, name: 'GameCube Consoles', localCategoryId: 16},
    {id: 17, name: 'Switch Consoles', localCategoryId: 17},
    {id: 18, name: 'Switch Games', localCategoryId: 18},
    {id: 19, name: 'Virtual Boy Consoles', localCategoryId: 19},
    {id: 20, name: 'Virtual Boy Software', localCategoryId: 20},
    {id: 21, name: 'Wii Consoles', localCategoryId: 21},
    {id: 22, name: 'Wii Games', localCategoryId: 22},
    {id: 23, name: 'Wii U Consoles', localCategoryId: 23},
    {id: 24, name: 'Wii U Consoles', localCategoryId: 24},
    {id: 25, name: 'Dreamcast Consoles', localCategoryId: 25},
    {id: 26, name: 'Dreamcast Games', localCategoryId: 26},
    {id: 27, name: 'Game Gear Consoles', localCategoryId: 27},
    {id: 28, name: 'Game Gear Games', localCategoryId: 28},
    {id: 29, name: 'Master System Consoles', localCategoryId: 29},
    {id: 30, name: 'Master System Software', localCategoryId: 30},
    {id: 31, name: 'Mega 32X Consoles', localCategoryId: 31},
    {id: 32, name: 'Mega 32X Software', localCategoryId: 32},
    {id: 33, name: 'Mega-CD Hardware', localCategoryId: 33},
    {id: 34, name: 'Mega-CD Software', localCategoryId: 34},
    {id: 35, name: 'Mega Drive Consoles', localCategoryId: 35},
    {id: 36, name: 'Mega Drive Software', localCategoryId: 36},
    {id: 37, name: 'Sega Saturn Consoles', localCategoryId: 37},
    {id: 38, name: 'Sega Saturn Games', localCategoryId: 38},
    {id: 39, name: 'Super NES Consoles', localCategoryId: 39},
    {id: 40, name: 'Super NES Software', localCategoryId: 40},
    {id: 41, name: 'Playstation1 Consoles', localCategoryId: 41},
    {id: 42, name: 'Playstation1 Games', localCategoryId: 42},
    {id: 43, name: 'Playstation2 Consoles', localCategoryId: 43},
    {id: 44, name: 'Playstation2 Games', localCategoryId: 44},
    {id: 45, name: 'Playstation3 Consoles', localCategoryId: 45},
    {id: 46, name: 'Playstation3 Games', localCategoryId: 46},
    {id: 47, name: 'Playstation4 Consoles', localCategoryId: 47},
    {id: 48, name: 'Playstation4 Games', localCategoryId: 48},
    {id: 49, name: 'Playstation5 Consoles', localCategoryId: 49},
    {id: 50, name: 'Playstation5 Games', localCategoryId: 50},
    {id: 51, name: 'PSP Consoles', localCategoryId: 51},
    {id: 52, name: 'PSP Games', localCategoryId: 52},
    {id: 53, name: 'PS Vita Consoles', localCategoryId: 53},
    {id: 54, name: 'PS Vita Games', localCategoryId: 54},
    {id: 55, name: 'PC Hardware', localCategoryId: 55},
    {id: 56, name: 'PC Games', localCategoryId: 56},
    {id: 57, name: 'Xbox Consoles', localCategoryId: 57},
    {id: 58, name: 'Xbox Games', localCategoryId: 58},
    {id: 59, name: 'Xbox 360 Consoles', localCategoryId: 59},
    {id: 60, name: 'Xbox 360 Games', localCategoryId: 60},
    {id: 61, name: 'Xbox One Consoles', localCategoryId: 61},
    {id: 62, name: 'Xbox One Games', localCategoryId: 62},
    {id: 63, name: 'Xbox Series Consoles', localCategoryId: 63},
    {id: 64, name: 'Xbox Series Games', localCategoryId: 64},
    {id: 65, name: 'Other', localCategoryId: 65 },
];
